import Head from 'next/head';
import Homebanner from '../components/Homebanner';
import Products from '../components/Products';
import Merchandise from '../components/Merchandise';
import Technology from '../components/Technology';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Fit-Grow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href='/fitgrow-icon.png'/>
      </Head>
      <Homebanner />
      <Products />
      <Merchandise />
      <Technology />
      <Footer />
    </>
  )
}
